on:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-node@v2
        with:
          cache: npm
          node-version: 16
      - run: npm ci
      - run: npm run generate
      - run: |
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -a -m 'Regenerate types' && git push
          fi
